# Generated by Django 2.0.1 on 2018-01-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_productinbasket_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinbasket',
            name='image',
        ),
    ]
