# Generated by Django 2.0.1 on 2018-02-23 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20180222_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Товар в заказе', 'verbose_name_plural': 'Товары в заказе'},
        ),
        migrations.RenameField(
            model_name='productinorder',
            old_name='nmb',
            new_name='qnty',
        ),
        migrations.RenameField(
            model_name='productinorder',
            old_name='total_price',
            new_name='total_amount',
        ),
    ]
