# Generated by Django 2.0.1 on 2018-01-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_price_with_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_with_discount',
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
