# Generated by Django 2.0.1 on 2018-01-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20180130_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_on_demand',
            field=models.BooleanField(default=False),
        ),
    ]
