# Generated by Django 2.0.3 on 2018-03-29 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='receiver_name',
        ),
    ]
