# Generated by Django 2.0.1 on 2018-02-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='banned',
            new_name='is_banned',
        ),
        migrations.AlterField(
            model_name='customer',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='register_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
