# Generated by Django 2.0.1 on 2018-02-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180213_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='activation_link',
            new_name='activation_key',
        ),
        migrations.AddField(
            model_name='profile',
            name='key_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
