# Generated by Django 2.0.1 on 2018-02-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180214_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
