# Generated by Django 2.0.3 on 2018-03-12 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20180223_0744'),
        ('accounts', '0011_auto_20180220_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='delivery_area',
            field=models.OneToOneField(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.OrderDeliveryArea'),
        ),
        migrations.AddField(
            model_name='profile',
            name='delivery_city',
            field=models.OneToOneField(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.OrderDeliveryCity'),
        ),
    ]
