# Generated by Django 2.0.3 on 2018-03-28 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180312_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='receiver_name',
        ),
    ]
