# Generated by Django 2.0.1 on 2018-01-23 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_productinbasket_session_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinbasket',
            old_name='qnty',
            new_name='nmb',
        ),
        migrations.RenameField(
            model_name='productinorder',
            old_name='qnty',
            new_name='nmb',
        ),
    ]
