# Generated by Django 2.0.1 on 2018-01-26 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180126_0943'),
        ('orders', '0008_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductImage'),
        ),
    ]
