# Generated by Django 2.0.1 on 2018-02-02 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_productinbasket_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinbasket',
            old_name='nmb',
            new_name='qnty',
        ),
    ]
