# Generated by Django 2.0.1 on 2018-02-20 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20180220_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.City'),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Region'),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.State'),
        ),
    ]
