# Generated by Django 2.0.2 on 2018-02-21 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20180220_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='city',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='region',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='state',
        ),
    ]
