# Generated by Django 2.0.1 on 2018-02-21 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20180221_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='area',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
