# Generated by Django 2.0.1 on 2018-02-22 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20180222_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDeliveryArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('area_ref', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Регион доставки',
                'verbose_name_plural': 'Регионы доставки',
            },
        ),
        migrations.CreateModel(
            name='OrderDeliveryCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('city_ref', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('area', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.OrderDeliveryArea')),
            ],
            options={
                'verbose_name': 'Город доставки',
                'verbose_name_plural': 'Города доставки',
            },
        ),
    ]
