# Generated by Django 2.0.1 on 2018-02-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_orderdeliveryarea_orderdeliverycity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdeliveryarea',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderdeliverycity',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
