# Generated by Django 2.0.3 on 2018-03-19 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinbasket',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productinbasket',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductInBasket',
        ),
        migrations.DeleteModel(
            name='ProductInOrder',
        ),
    ]
