# Generated by Django 2.0.1 on 2018-01-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180122_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_type',
            new_name='category',
        ),
    ]
