# Generated by Django 2.0.1 on 2018-01-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_is_on_demand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_on_stock',
            field=models.BooleanField(default=True),
        ),
    ]
