# Generated by Django 2.0.1 on 2018-02-09 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20180119_1200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
